
export const MovieData=[
    {
        id: 0,
            image: "https://occ-0-2705-2706.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUboxFv3vWSPIOvGXm7DXUZKDSjTQMPOwlAvacSdioqkj3AyCAUzF0JTsPdINoYvPCsCihqCZkaKBnZzYaTIziIqvGo0.jpg",
            rating: 4,
            name: " 365 Days ",
            date: "2020",
            type: "Drama",
            decreptions: "Massimo is a member of the Sicilian Mafia family and Laura is a sales director. She does not expect that on a trip to Sicily trying to save her relationship, Massimo will kidnap her and give her 365 days to fall in love with him.", 
            Video:"https://www.youtube.com/embed/WnIL4o6_D8M",    
    },
    {
        id: 1,
            image: "https://upload.wikimedia.org/wikipedia/en/thumb/8/89/Extraction_%282020_film%29.png/220px-Extraction_%282020_film%29.png",
            rating: 5,
            name: "Extraction",
            date: "2020",
            type:"Action",
            decreptions: "Tyler Rake, a fearless black market mercenary, embarks on the most deadly extraction of his career when he's enlisted to rescue the kidnapped son of an imprisoned international crime lord.",
            Video:"https://www.youtube.com/embed/V95ZyU3QMic" ,  
    },
    {
        id: 2,
            image: "https://m.media-amazon.com/images/M/MV5BYWVmYTFjODItOTY2Ni00NDhhLTk1ZDYtMzBmOGFhZTMyY2Q0XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
            rating: 3,
            name:"Holidate",
            date: "2020",
            type: "Romance",
            decreptions: "Fed up with being single on holidays, two strangers agree to be each other's platonic plus-ones all year long, only to catch real feelings along the way.",
            Video:"" ,  
    },
    {
        id: 3,
            image:"https://upload.wikimedia.org/wikipedia/en/3/31/John_Wick_Chapter_Two.png",
            rating: 4,
            name: "John Wick 2",
            date:"2017",
            type:"Action",
            decreptions: "After returning to the criminal underworld to repay a debt, John Wick discovers that a large bounty has been put on his life.",
            Video:"" ,  
    },
    {
        id: 4,
            image: "https://upload.wikimedia.org/wikipedia/en/b/b3/Project_Power_poster.jpeg",
            rating:2,
            name:"Project Power",
            date:"2020",
            type:"Action",
            decreptions:"When a pill that gives its users unpredictable superpowers for five minutes hits the streets of New Orleans, a teenage dealer and a local cop must team with an ex-soldier to take down the group responsible for its creation.", 
            Video: "",  
    },
    {
        id: 5,
            image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/wonder-woman-1984-poster-1606931235.jpg?resize=480:*",
            rating: 2,
            name:"Wonder Women",
            date:"2017",
            type: "Action",
            decreptions: "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.",
            Video: "",  
    },
]
    


